name: build

on:
  release:
    types:
      - published

jobs:
  build:
    name: build Python ${{ matrix.python-version }} wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.x' ]
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: load cached `~/.local`
        uses: actions/cache@v2.1.6
        with:
          path: ~/.local
          key: ${{ runner.os }}-python${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-python${{ matrix.python-version }}-
      - name: build wheel
        run: poetry build
      - name: save wheel
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*
  deploy:
    name: publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: retrieve build
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: deploy build to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
