name: tests

on: [ push ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: load cached `~/.local`
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: ${{ runner.os }}-python${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-python${{ matrix.python-version }}-
      - name: install dependencies
        run: | 
          pip install flake8
          poetry install
      - name: lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  pip:
    needs: lint
    name: test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.6', '3.x' ]
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: load cached `~/.local`
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: ${{ runner.os }}-python${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-python${{ matrix.python-version }}-
      - name: Install dependencies
        run: poetry install --extras testing
      - name: run tests
        if: matrix.python-version != '3.x' && matrix.os != 'ubuntu-latest'
        run: pytest --numprocesses auto
      - name: run tests with coverage
        if: matrix.python-version == '3.x' && matrix.os == 'ubuntu-latest'
        run: pytest --numprocesses auto --cov ./ --cov-report xml:coverage.xml
      - name: upload coverage to Codecov
        if: matrix.python-version == '3.x' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
  conda:
    needs: lint
    name: test Anaconda ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.6', '3.x' ]
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: load cached `~/.local`
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: ${{ runner.os }}-conda${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-conda${{ matrix.python-version }}-
      - name: install dependencies
        run: conda install pytest pytest-xdist -y
      - name: run tests
        run: pytest --numprocesses auto

